import { _ as S } from "./Dd5D4KLK.js";
import { _ as P } from "./B9LdsyXf.js";
import { f as b, o as n, c as m, b as _, w as h, a as e, g as s, t as u, h as x, d as B, i as g, j as it, k as w, r as lt, F as $, l as k, m as rt, n as zt, q as At, s as L, v as at, u as N, S as X, x as dt, y as J, z as mt, A as pt, B as Nt } from "./DkmPUy5X.js";
import { c as I } from "./DxEWXAgR.js";
import { _ as H } from "./DlAUqK2U.js";
import { _ as F } from "./I81M9Kyj.js";
import { u as v } from "./CyLbGF9c.js";
import { I as Ft, S as ut, _ as Et, P as Vt, C as Ot, a as Ut, b as Wt, c as qt } from "./BawP50mX.js";
import { _ as st } from "./Dnw0Xoc2.js";
import { _ as j } from "./BEsmpgYe.js";
import { _ as T } from "./Qu9TemJM.js";
import { _ as Qt, a as Yt, b as Gt, u as Jt, c as Xt, d as Zt, e as Kt } from "./CXAAPvCW.js";
import { S as R } from "./D6krPanI.js";
import { I as te } from "./tzY1PJnp.js";
import { _ as ee, a as se, b as _t } from "./DuZ18o7B.js";
import { I as ot, _ as ne, a as ae, b as oe, c as ce, d as ie, e as le, f as re } from "./CWSSiit7.js";
import { _ as de } from "./CARH67x1.js";
import { _ as me, a as pe } from "./Cus4rhJi.js";
import { u as ue } from "./DH0SFBRw.js";
import { t as et } from "./_UnaSTDn.js";
import { _ as _e } from "./B_FKmFTg.js";
import { _ as xe } from "./phlnR9ZB.js";
import { I as he } from "./BpItg_TL.js";
import { u as xt } from "./CfuTB1_-.js";
import { u as ge, a as fe } from "./weCuNnw3.js";
import { R as ct } from "./DavNGxsQ.js";
import { u as be } from "./C0L0qvym.js";
import { u as ye } from "./BaXB5ET8.js";
import { u as ht } from "./DLlB40F_.js";
import { P as ve } from "./lkGBfNza.js";
import { u as we } from "./Dvct4J4a.js";
import "./DudrQUT2.js";
import "./C1LltJXx.js";
import "./BK49Amkq.js";
import "./DiJDe4w_.js";
import "./ziA4Pi5N.js";
import "./BJuvBWP6.js";
var $e = I("brand-speedtest", "IconBrandSpeedtest", [
        ["path", { d: "M5.636 19.364a9 9 0 1 1 12.728 0", key: "svg-0" }],
        ["path", { d: "M16 9l-4 4", key: "svg-1" }]
    ]),
    ke = I("building-broadcast-tower", "IconBuildingBroadcastTower", [
        ["path", { d: "M12 12m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0", key: "svg-0" }],
        ["path", { d: "M16.616 13.924a5 5 0 1 0 -9.23 0", key: "svg-1" }],
        ["path", { d: "M20.307 15.469a9 9 0 1 0 -16.615 0", key: "svg-2" }],
        ["path", { d: "M9 21l3 -9l3 9", key: "svg-3" }],
        ["path", { d: "M10 19h4", key: "svg-4" }]
    ]),
    Ce = I("chart-bar", "IconChartBar", [
        ["path", { d: "M3 12m0 1a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v6a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1z", key: "svg-0" }],
        ["path", { d: "M9 8m0 1a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v10a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1z", key: "svg-1" }],
        ["path", { d: "M15 4m0 1a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v14a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1z", key: "svg-2" }],
        ["path", { d: "M4 20l14 0", key: "svg-3" }]
    ]),
    Le = I("circle-check", "IconCircleCheck", [
        ["path", { d: "M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0", key: "svg-0" }],
        ["path", { d: "M9 12l2 2l4 -4", key: "svg-1" }]
    ]),
    Be = I("cpu", "IconCpu", [
        ["path", { d: "M5 5m0 1a1 1 0 0 1 1 -1h12a1 1 0 0 1 1 1v12a1 1 0 0 1 -1 1h-12a1 1 0 0 1 -1 -1z", key: "svg-0" }],
        ["path", { d: "M9 9h6v6h-6z", key: "svg-1" }],
        ["path", { d: "M3 10h2", key: "svg-2" }],
        ["path", { d: "M3 14h2", key: "svg-3" }],
        ["path", { d: "M10 3v2", key: "svg-4" }],
        ["path", { d: "M14 3v2", key: "svg-5" }],
        ["path", { d: "M21 10h-2", key: "svg-6" }],
        ["path", { d: "M21 14h-2", key: "svg-7" }],
        ["path", { d: "M14 21v-2", key: "svg-8" }],
        ["path", { d: "M10 21v-2", key: "svg-9" }]
    ]),
    Te = I("currency-dollar", "IconCurrencyDollar", [
        ["path", { d: "M16.7 8a3 3 0 0 0 -2.7 -2h-4a3 3 0 0 0 0 6h4a3 3 0 0 1 0 6h-4a3 3 0 0 1 -2.7 -2", key: "svg-0" }],
        ["path", { d: "M12 3v3m0 12v3", key: "svg-1" }]
    ]),
    Me = I("exclamation-circle", "IconExclamationCircle", [
        ["path", { d: "M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0", key: "svg-0" }],
        ["path", { d: "M12 9v4", key: "svg-1" }],
        ["path", { d: "M12 16v.01", key: "svg-2" }]
    ]),
    Se = I("hand-click", "IconHandClick", [
        ["path", { d: "M8 13v-8.5a1.5 1.5 0 0 1 3 0v7.5", key: "svg-0" }],
        ["path", { d: "M11 11.5v-2a1.5 1.5 0 0 1 3 0v2.5", key: "svg-1" }],
        ["path", { d: "M14 10.5a1.5 1.5 0 0 1 3 0v1.5", key: "svg-2" }],
        ["path", { d: "M17 11.5a1.5 1.5 0 0 1 3 0v4.5a6 6 0 0 1 -6 6h-2h.208a6 6 0 0 1 -5.012 -2.7l-.196 -.3c-.312 -.479 -1.407 -2.388 -3.286 -5.728a1.5 1.5 0 0 1 .536 -2.022a1.867 1.867 0 0 1 2.28 .28l1.47 1.47", key: "svg-3" }],
        ["path", { d: "M5 3l-1 -1", key: "svg-4" }],
        ["path", { d: "M4 7h-1", key: "svg-5" }],
        ["path", { d: "M14 3l1 -1", key: "svg-6" }],
        ["path", { d: "M15 6h1", key: "svg-7" }]
    ]),
    Ie = I("playstation-x", "IconPlaystationX", [
        ["path", { d: "M12 21a9 9 0 0 0 9 -9a9 9 0 0 0 -9 -9a9 9 0 0 0 -9 9a9 9 0 0 0 9 9z", key: "svg-0" }],
        ["path", { d: "M8.5 8.5l7 7", key: "svg-1" }],
        ["path", { d: "M8.5 15.5l7 -7", key: "svg-2" }]
    ]),
    je = I("question-mark", "IconQuestionMark", [
        ["path", { d: "M8 8a3.5 3 0 0 1 3.5 -3h1a3.5 3 0 0 1 3.5 3a3 3 0 0 1 -2 3a3 4 0 0 0 -2 4", key: "svg-0" }],
        ["path", { d: "M12 19l0 .01", key: "svg-1" }]
    ]);
const De = { class: "sticky top-20 z-20" },
    Pe = { class: "flex w-full" },
    He = { class: "ml-3 w-full" },
    Re = { class: "w-full text-body1 text-red-main" },
    ze = ["innerHTML"],
    Ae = b({ __name: "UnavailableBanner", props: { data: {} }, setup(l) { const t = l; return (o, c) => { const r = S,
                    d = P; return n(), m("div", De, [_(d, { class: "bg-error-light bg-red-light px-6 py-5" }, { default: h(() => [e("div", Pe, [_(s(Me), { class: "text-red-main" }), e("div", He, [e("div", Re, u(t.data.title), 1), e("span", { class: "w-full text-justify text-body1 text-text-primary", innerHTML: t.data.description }, null, 8, ze), t.data.availableLink ? (n(), x(r, { key: 0, classes: "text-subtitle1 text-text-blue", "navigation-object": { link: t.data.availableLink.link } }, { default: h(() => [B(u(t.data.availableLink.content), 1)]), _: 1 }, 8, ["navigation-object"])) : g("", !0), B(". ")])])]), _: 1 })]) } } }),
    Ne = H(Ae, [
        ["__scopeId", "data-v-22b8fe9d"]
    ]),
    Fe = { class: "bg" },
    Ee = b({ __name: "BaseResponsiveBackgroud", props: { image: {} }, setup(l) { it(r => ({ "4a66a45b": s(o), "6983db45": s(c) })); const t = l,
                o = w(() => `url(${v(t.image.sm.src)})`),
                c = w(() => `url(${v(t.image.lg.src)})`); return (r, d) => (n(), m("div", Fe, [lt(r.$slots, "default", {}, void 0, !0)])) } }),
    Ve = H(Ee, [
        ["__scopeId", "data-v-5451dc91"]
    ]),
    Oe = { class: "py-10 sm:py-[71px] lg:py-[100px]" },
    Ue = { class: "mb-4 flex max-w-[1200px] flex-col text-center sm:mb-[30px] md:mb-6 md:max-w-[808px] lg:mb-[111px] lg:max-w-[1104px] xl:mb-[270px]" },
    We = { class: "mb-4 w-full text-h5 text-text-secondary" },
    qe = { class: "mb-4 text-caption text-h4 text-text-primary sm:mb-8 sm:text-h2 sm:leading-[55px] lg:text-h1" },
    Qe = { class: "text-h6 text-text-secondary" },
    Ye = { class: "grid grid-cols-1 gap-x-[72px] gap-y-6 rounded-xl bg-white-default p-8 shadow-1 sm:grid-cols-2 sm:gap-x-6 lg:grid-cols-4" },
    Ge = { class: "mr-2 flex h-5 w-5 items-center justify-center rounded-[50%] bg-primary-main" },
    Je = { class: "mr-1 whitespace-nowrap text-subtitle1" },
    Xe = { class: "whitespace-nowrap text-body1" },
    Ze = b({ __name: "HeroCloud", props: { data: {} }, setup(l) { const t = { "question-mark": je, "currency-dollar": Te, server: Ft, "building-broadcast-tower": ke, "hand-click": Se, cpu: Be, "chart-bar": Ce, "brand-speedtest": $e },
                o = l,
                c = r => t[r]; return (r, d) => { const i = F,
                    p = Ve,
                    f = P; return n(), x(f, null, { default: h(() => [_(p, { image: o.data.image }, { default: h(() => [_(i, { class: "relative mb-80 flex h-[516px] flex-wrap justify-center sm:mb-0 sm:h-[633px] md:h-[600px] lg:h-[690px] xl:h-[874px]" }, { default: h(() => [e("div", Oe, [e("div", Ue, [e("h1", We, u(o.data.title), 1), e("h2", qe, u(o.data.description), 1), e("div", null, [e("p", Qe, u(o.data.subDescription), 1)])]), e("div", Ye, [(n(!0), m($, null, k(o.data.features, a => (n(), m("div", { key: a.title, class: "flex items-center text-text-primary" }, [e("span", Ge, [(n(), x(rt(c(a.icon)), { class: "h-4 w-4 text-white-default" }))]), e("span", Je, u(a.title), 1), e("span", Xe, u(a.description), 1)]))), 128))])])]), _: 1 })]), _: 1 }, 8, ["image"])]), _: 1 }) } } }),
    Ke = { class: "flex w-full flex-wrap max-md:space-y-6 md:justify-center lg:space-x-7" },
    ts = { class: "flex items-center whitespace-pre md:justify-center" },
    es = { class: "ml-4 flex w-36 flex-col content-between items-start justify-center lg:w-auto" },
    ss = { class: "text-subtitle1 text-text-primary sm:text-h6" },
    ns = { class: "text-body2 text-primary-main" },
    as = "Created VPS",
    os = b({ __name: "PerformanceFeatures", props: { features: {} }, setup(l) { const t = l,
                o = w(() => t.features.map(c => c.description.includes(as) ? { title: zt(At()), description: c.description, image: c.image } : c)); return (c, r) => { const d = T,
                    i = Qt; return n(), x(i, { class: "flex max-w-5xl justify-center bg-white-default px-2 py-8 sm:px-9" }, { default: h(() => [e("div", Ke, [(n(!0), m($, null, k(s(o), (p, f) => (n(), m("div", { key: p.description, class: L(["flex w-full justify-center sm:w-1/2 md:w-1/3 lg:w-auto", { "max-lg:mt-8": f >= t.features.length - 2 }]) }, [e("div", ts, [_(d, { class: "h-[50px] w-[50px]", src: ("useReplaceDomain" in c ? c.useReplaceDomain : s(v))(p.image.src), alt: p.image.alt }, null, 8, ["src", "alt"]), e("div", es, [e("p", ss, u(p.title), 1), e("p", ns, u(p.description), 1)])])], 2))), 128))])]), _: 1 }) } } }),
    cs = { class: "flex w-full justify-center self-end py-8" },
    is = { class: "flex max-w-[1200px] flex-wrap justify-between text-center md:max-w-[808px] lg:max-w-[1104px]" },
    ls = { class: "w-full" },
    rs = { class: "text-caption leading-[28px] text-white-80 sm:text-h6" },
    ds = { class: "w-full text-center text-caption text-h4 leading-[36px] text-white-default sm:text-h2 sm:leading-[55px] lg:text-h1 lg:leading-[60px]" },
    ms = { class: "mt-4 w-full sm:mt-6 md:mt-8" },
    ps = { class: "text-body1 text-white-80 sm:text-h6" },
    us = { class: "-mb-56 flex w-full justify-center self-end sm:-mb-[120px] md:-mb-[100px] lg:-mb-14" },
    _s = b({ __name: "HeroLanding", props: { data: {}, basePrice: {} }, setup(l) { const t = l,
                o = `background-image: url(${v(t.data.image.src)})`; return (c, r) => { const d = st,
                    i = j,
                    p = os,
                    f = F,
                    a = P; return n(), x(a, { classes: "bg-hero-landing", style: o }, { default: h(() => [_(f, { class: "mb-80 flex h-[596px] flex-wrap justify-center sm:mb-60 sm:h-[633px] md:mb-0 md:h-[520px] lg:h-[570px] xl:h-[720px]" }, { default: h(() => [e("div", cs, [e("div", is, [e("div", ls, [e("h1", rs, u(t.data.title), 1)]), e("h2", ds, u(t.data.description), 1), e("div", ms, [e("p", ps, u(s(at)(t.data.subDescription, t.basePrice)), 1)]), _(i, { classes: "flex mr-auto ml-auto mt-4 sm:mt-6 md:mt-8 lg:mt-10 text-btn", mode: "secondary", padding: "large", "text-size": "text-btnLarge" }, { default: h(() => [_(d, { id: s(R).LandingHeroStartingButton, class: "flex", href: "#pricing" }, { default: h(() => [e("span", null, u(s(at)(t.data.action.content, t.basePrice)), 1), _(s(te), { size: 24, class: "ml-2" })]), _: 1 }, 8, ["id"])]), _: 1 })])]), e("div", us, [_(p, { features: t.data.features }, null, 8, ["features"])])]), _: 1 })]), _: 1 }) } } }),
    xs = H(_s, [
        ["__scopeId", "data-v-01314aad"]
    ]),
    hs = { id: "pricing", class: "overflow-hidden rounded-[40px] bg-gradient-to-b from-primary-soft to-white-default" },
    gs = { class: "bg-[url('/public/service-information/linear-bg.png')] bg-[length:190px] bg-right-top bg-no-repeat px-[18px] py-8 sm:px-6 sm:py-10 md:mb-24 md:bg-[length:unset] md:px-12 md:py-14 lg:mb-40" },
    fs = { class: "mb-6 text-h4 text-text-primary sm:text-h3 md:text-h2" },
    bs = { class: "mb-6 text-body2 text-text-secondary sm:text-body1" },
    ys = { class: "flex flex-row flex-wrap" },
    vs = { class: "flex items-center" },
    ws = ["innerHTML"],
    $s = { class: "ml-3 text-h6 text-text-primary" },
    ks = { class: "mt-4 text-body2 text-text-secondary sm:text-body1" },
    Cs = { class: "flex flex-col items-center justify-center gap-2 sm:flex-row" },
    Ls = b({ __name: "ServiceInformation", props: { data: {} }, setup(l) { const t = l; return (o, c) => { const r = j,
                    d = S; return n(), m("div", hs, [e("div", gs, [e("h2", fs, u(t.data.title), 1), e("p", bs, u(t.data.description), 1), e("div", ys, [(n(!0), m($, null, k(t.data.items, (i, p) => (n(), m("div", { key: i.id, class: L(["mb-6 flex-[0_0_100%] lg:mb-12 lg:flex-[0_0_50%]", p % 2 === 0 ? "lg:pr-6" : ""]) }, [e("div", vs, [e("div", { innerHTML: i.icon }, null, 8, ws), e("h3", $s, u(i.title), 1)]), e("p", ks, u(i.description), 1)], 2))), 128))]), e("div", Cs, [(n(!0), m($, null, k(t.data.actionButtons, i => (n(), x(d, { key: i.content, "navigation-object": { link: i.link }, classes: "w-full sm:w-[180px]" }, { default: h(() => [_(r, { mode: i.mode, class: "flex w-full justify-center" }, { default: h(() => [B(u(i.content), 1)]), _: 2 }, 1032, ["mode"])]), _: 2 }, 1032, ["navigation-object"]))), 128))])])]) } } }),
    Bs = { class: "relative flex flex-col items-center rounded-xl bg-primary-main p-4 text-white-default sm:p-6 md:flex-row md:p-10 lg:px-20 lg:py-8" },
    Ts = ["innerHTML"],
    Ms = b({ __name: "HostAdvice", props: { data: {} }, setup(l) { const t = l; return (o, c) => { const r = T; return n(), m("div", Bs, [_(r, { src: "/hostAdvice/cloud.svg", class: "absolute right-0 top-0 w-56 lg:w-auto", width: "338", height: "197", alt: "cloud" }), _(r, { src: ("useReplaceDomain" in o ? o.useReplaceDomain : s(v))(t.data.image.src), alt: t.data.image.alt, width: "198", height: "198", class: "w-28 sm:w-32 md:h-40 md:w-40 lg:h-[198px] lg:w-[198px]" }, null, 8, ["src", "alt"]), e("p", { class: "relative z-10 mt-3 text-center text-body1 md:ml-8 md:mt-0 md:text-justify", innerHTML: t.data.description }, null, 8, Ts)]) } } }),
    Ss = { class: "" },
    Is = { class: "text-center text-h2 text-text-primary" },
    js = { class: "mt-8 text-center text-body1 text-text-secondary" },
    Ds = { class: "relative rounded-lg bg-white-default shadow-1" },
    Ps = e("div", { class: "absolute -top-[27px] left-1/2 z-0 hidden h-[calc(100%+54px)] w-1/3 -translate-x-1/2 rounded-lg bg-primary-soft shadow-1 md:block" }, null, -1),
    Hs = { class: "relative z-10 flex flex-wrap" },
    Rs = e("span", { class: "hidden sm:flex md:w-1/3" }, null, -1),
    zs = { class: "h-14 w-full bg-primary-soft px-8 py-4 text-center text-subtitle1 font-bold text-text-primary md:w-1/3 md:bg-inherit md:text-left md:text-text-secondary" },
    As = { key: 0, class: "flex h-14 w-1/2 justify-center px-8 py-4 md:w-1/3" },
    Ns = { key: 1, class: "flex h-14 w-1/2 justify-center px-8 py-4 text-body1 capitalize text-text-secondary md:w-1/3" },
    Fs = { key: 2, class: "flex h-14 w-1/2 justify-center px-8 py-4 md:w-1/3" },
    Es = { key: 3, class: "flex h-14 w-1/2 justify-center px-8 py-4 text-body1 capitalize text-text-secondary md:w-1/3" },
    Vs = b({ __name: "LandingVs", props: { data: {} }, setup(l) { const t = l; return (o, c) => { const r = F,
                    d = P; return n(), m("div", Ss, [_(d, { classes: "bg-[url('assets/images/vs/Windows-1920.png')] sm:bg-cover bg-inherit md:bg-center bg-right bg-no-repeat " }, { default: h(() => [_(r, { class: "relative pb-52 pt-24" }, { default: h(() => [e("h2", Is, u(t.data.title), 1), e("p", js, u(t.data.description), 1)]), _: 1 })]), _: 1 }), _(r, { classes: "-mt-28 !px-0" }, { default: h(() => [e("div", Ds, [Ps, e("div", Hs, [Rs, (n(!0), m($, null, k(t.data.columnNames, i => (n(), m("span", { key: i.id, class: "flex h-20 w-1/2 items-center justify-center px-1 text-center text-h5 text-text-primary sm:px-0 sm:text-left md:w-1/3" }, u(i.title), 1))), 128))]), (n(!0), m($, null, k(t.data.items, i => (n(), m("div", { key: i.title, class: "relative z-10 flex flex-wrap border-b border-grey-map last:border-0" }, [e("span", zs, u(i.title), 1), i.content[1] === "Done" ? (n(), m("span", As, [_(s(ot), { class: "text-green-main" })])) : (n(), m("span", Ns, u(i.content[1]), 1)), i.content[2] === "Done" ? (n(), m("span", Fs, [_(s(ot), { class: "text-green-main" })])) : (n(), m("span", Es, u(i.content[2]), 1))]))), 128))])]), _: 1 })]) } } }),
    Os = { class: "mb-8 flex max-w-[1200px] flex-col sm:items-center md:items-start lg:ml-auto lg:mr-auto lg:flex-row" },
    Us = { class: "xl:mr-15 text-left text-h4 text-text-primary sm:text-h3 md:text-h2 lg:mr-12 lg:w-[380px]" },
    Ws = ["innerHTML"],
    qs = { class: "max-w-[1100px] lg:ml-auto lg:mr-auto lg:flex" },
    Qs = b({ __name: "LandingFeaturesCarousel", props: { data: {} }, setup(l) { const { isDesktop: t, isMobileOrTablet: o } = ue(), c = { 320: { itemsToShow: 1, snapAlign: "start" }, 600: { itemsToShow: 2, snapAlign: "start" }, 1200: { itemsToShow: 3, itemsToScroll: 3, snapAlign: "start" } }; return (r, d) => { const i = Yt,
                    p = ut,
                    f = Et,
                    a = P; return n(), x(a, { classes: "px-6 py-16 sm:px-8 sm:py-[100px] lg:py-25 md:px-11 lg:px-12 bg-primary-soft" }, { default: h(() => [e("div", Os, [e("h2", Us, u(r.data.title), 1), e("p", { class: "text-justify text-body1 text-text-secondary lg:w-3/4", innerHTML: r.data.description }, null, 8, Ws)]), e("div", qs, [_(f, { "nav-button-height": "95%", "nav-button-width": "40px", "nav-button-border-radius": "4px", left: "-50px", right: "-50px", top: "3px", "background-color": s(et).theme.colors.primary.light, "has-navigation": s(t), "has-pagination": s(o), "wrap-around": s(o), breakpoints: c, "navigation-button-class": s(R).BlueSectionNavigationButton }, { default: h(() => [(n(!0), m($, null, k(r.data.features, M => (n(), x(p, { key: M.title, class: "py-1.5 lg:pl-2.5" }, { default: h(() => [_(i, { class: "ml-1 mr-4", "title-classes": "text-h6", image: M.image, title: M.title, description: M.description }, null, 8, ["image", "title", "description"])]), _: 2 }, 1024))), 128))]), _: 1 }, 8, ["background-color", "has-navigation", "has-pagination", "wrap-around", "navigation-button-class"])])]), _: 1 }) } } }),
    Ys = { class: "flex flex-col lg:flex-row" },
    Gs = { class: "mr-6 flex w-full flex-col lg:w-1/2" },
    Js = { class: "mb-8 text-center text-h4 text-text-primary sm:text-h3 md:text-left md:text-h2" },
    Xs = ["innerHTML"],
    Zs = { class: "mb-6 flex w-full flex-wrap justify-center gap-4 lg:justify-start" },
    Ks = { class: "flex w-full justify-center lg:w-1/2" },
    tn = b({ __name: "LandingHowTo", props: { data: {} }, setup(l) { const t = l; return (o, c) => { const r = j,
                    d = st,
                    i = T; return n(), m("div", Ys, [e("div", Gs, [e("h2", Js, u(t.data.title), 1), e("p", { class: "subtitle-1 mb-6 text-justify text-text-secondary", innerHTML: t.data.description }, null, 8, Xs), e("div", Zs, [(n(!0), m($, null, k(t.data.actions, p => (n(), x(d, { key: p.link, class: "w-full sm:w-64 lg:w-[calc(50%-8px)]", to: p.link }, { default: h(() => [_(r, { class: "w-full" }, { default: h(() => [B(u(p.content), 1)]), _: 2 }, 1024)]), _: 2 }, 1032, ["to"]))), 128))])]), e("div", Ks, [_(i, { class: "w-full max-w-[760px]", width: "296px", height: "288px", src: ("useReplaceDomain" in o ? o.useReplaceDomain : s(v))(t.data.image.src), alt: t.data.image.alt }, null, 8, ["src", "alt"])])]) } } }),
    en = ["innerHTML"],
    sn = b({ __name: "BaseSVG", props: { icon: {}, color: {} }, setup(l) { it(o => ({ "40f8861c": t.color })); const t = l; return (o, c) => (n(), m("span", { innerHTML: t.icon }, null, 8, en)) } }),
    nn = H(sn, [
        ["__scopeId", "data-v-47491c47"]
    ]),
    an = { class: "mb-20 sm:mb-24 lg:mb-36" },
    on = { class: "mb-6 text-h2 text-text-primary" },
    cn = { class: "lg:flex" },
    ln = { class: "mb-6 lg:w-[calc(100%-384px)]" },
    rn = { key: 0, class: "text-h6 text-text-primary" },
    dn = { class: "mt-2 text-body1 text-text-secondary" },
    mn = { class: "flex justify-center" },
    pn = b({ __name: "LandingWhenToBuy", props: { data: {} }, setup(l) { return (t, o) => { const c = nn,
                    r = st,
                    d = j,
                    i = xe,
                    p = T; return n(), m("div", an, [e("h2", on, u(t.data.title), 1), e("div", cn, [e("div", ln, [_(i, { items: t.data.items, "has-image": !0, "tab-style": `bg-white-default rounded w-1/${t.data.items.length} text-h6 sm:text-body1 ml-2 flex min-w-[188px] cursor-pointer flex-col items-center bg-white-default py-4 text-center shadow-1 first:ml-0`, "content-style": "bg-white-default flex flex-col justify-between items-start", "content-wrapper-style": "mt-4 h-full rounded-lg bg-white-default shadow-1", "wrapper-style": "[&>ul]:py-1" }, { header: h(({ tab: f, isActive: a }) => [_(c, { class: "mb-2", icon: f.image.src, color: a ? s(et).theme.colors.primary.main : s(et).theme.colors.grey[300] }, null, 8, ["icon", "color"])]), default: h(({ tab: f }) => [f.serviceDescriptionContent.title ? (n(), m("h4", rn, u(f.serviceDescriptionContent.title), 1)) : g("", !0), e("p", dn, u(f.serviceDescriptionContent.description), 1), f.serviceDescriptionContent.action ? (n(), x(d, { key: 1, size: "large", classes: "text-primary-main bg-primary-light mt-4 lg:mt-10 w-auto" }, { default: h(() => [_(r, { to: f.serviceDescriptionContent.action.link, class: L(s(R).MostPopularServicesAction) }, { default: h(() => [B(u(f.serviceDescriptionContent.action.content), 1)]), _: 2 }, 1032, ["to", "class"])]), _: 2 }, 1024)) : g("", !0)]), _: 1 }, 8, ["items", "tab-style"])]), e("div", mn, [_(p, { class: "hidden w-[384px] max-w-full sm:flex lg:ml-6", src: ("useReplaceDomain" in t ? t.useReplaceDomain : s(v))(t.data.image.src), alt: t.data.image.alt, width: "384", height: "401", loading: "lazy" }, null, 8, ["src", "alt"])])])]) } } }),
    un = { class: "lg:mx-auto lg:max-w-[1200px]" },
    _n = { class: "flex flex-col" },
    xn = { class: "mb-8 mr-auto text-h4 text-text-primary sm:text-h2 lg:max-w-[728px]" },
    hn = { class: "mb-3 flex w-full md:mb-10 lg:mr-6" },
    gn = { class: "mb-6 grid w-full grid-cols-2 gap-x-4 gap-y-3 sm:grid-cols-3 sm:gap-x-6 sm:gap-y-4 md:grid-cols-4 lg:mr-10 lg:w-2/3" },
    fn = { key: 0, class: "text-subtitle2 font-bold text-text-primary" },
    bn = { key: 1, class: "text-code text-text-secondary" },
    yn = { class: "flex h-[70px] justify-around rounded-lg px-6 py-3 shadow-1" },
    vn = b({ __name: "LandingPaymentMethods", props: { data: {} }, setup(l) { const t = l,
                o = d => d.title,
                c = d => d.description,
                r = d => o(d) && c(d); return (d, i) => { const p = T,
                    f = P; return n(), x(f, { class: "via-[rgba(221, 221, 255, 0) 99.42%] to-transparent bg-gradient-to-l from-[#d5d5ff] px-6 py-[60px] sm:px-8 md:px-12" }, { default: h(() => [e("div", un, [e("div", _n, [e("h2", xn, u(t.data.title), 1), e("div", hn, [e("div", gn, [(n(!0), m($, null, k(t.data.methods, a => (n(), m("div", { key: a.image.alt, class: L(["flex h-[70px] w-full items-center rounded bg-white-default px-2 py-3 shadow-1", { "justify-center": !r(a) }]) }, [_(p, { src: ("useReplaceDomain" in d ? d.useReplaceDomain : s(v))(a.image.src), class: L([{ "w-[36px]": r(a), "h-8 w-auto": !r(a) }, "mr-2"]), width: "26px" }, null, 8, ["src", "class"]), e("div", null, [o(a) ? (n(), m("p", fn, u(a.title), 1)) : g("", !0), c(a) ? (n(), m("p", bn, u(a.description), 1)) : g("", !0)])], 2))), 128))]), _(p, { src: ("useReplaceDomain" in d ? d.useReplaceDomain : s(v))(t.data.image.src), alt: t.data.image.alt, width: "342px", height: "336px", class: "hidden lg:block" }, null, 8, ["src", "alt"])])]), e("div", yn, [(n(!0), m($, null, k(t.data.footerImages, a => (n(), x(p, { key: a.alt, src: ("useReplaceDomain" in d ? d.useReplaceDomain : s(v))(a.src), class: "h-[50px] w-auto", width: "40", height: "50" }, null, 8, ["src"]))), 128))])])]), _: 1 }) } } }),
    wn = { class: "custom-carousel relative" },
    $n = { class: "mt-9 text-h4 sm:text-h3 md:text-h2" },
    kn = { class: "mr-2 text-text-primary" },
    Cn = { class: "text-secondary-main" },
    Ln = b({ __name: "BaseCustomCarousel", props: { wrapAround: { type: Boolean, default: !1 }, hasPagination: { type: Boolean, default: !0 }, itemsToShow: { default: 1 }, primaryTitle: { default: "" }, secondaryTitle: { default: "" } }, setup(l) { const t = l; return (o, c) => { const r = Gt,
                    d = P,
                    i = Vt,
                    p = Ot; return n(), m("div", wn, [_(d, null, { default: h(() => [_(r)]), _: 1 }), e("h2", $n, [e("span", kn, u(t.primaryTitle), 1), e("span", Cn, u(t.secondaryTitle), 1)]), _(p, { "items-to-show": t.itemsToShow, "wrap-around": t.wrapAround }, { addons: h(() => [t.hasPagination ? (n(), x(i, { key: 0 })) : g("", !0)]), default: h(() => [lt(o.$slots, "default", {}, void 0, !0)]), _: 3 }, 8, ["items-to-show", "wrap-around"])]) } } }),
    Bn = H(Ln, [
        ["__scopeId", "data-v-62539a70"]
    ]),
    Tn = { class: "flex w-full flex-col gap-6 py-8 text-left lg:flex-row" },
    Mn = { class: "mb-8 text-h4 text-text-primary" },
    Sn = { class: "mr-3 flex rounded-full bg-green-light p-1" },
    In = { class: "text-body1 text-text-secondary" },
    jn = { class: "flex justify-center" },
    Dn = b({ __name: "UseCaseCarousel", props: { data: {} }, setup(l) { const t = l; return (o, c) => { const r = T,
                    d = ut,
                    i = Bn; return n(), m("div", null, [_(i, { "primary-title": t.data.primaryTitle, "secondary-title": t.data.secondaryTitle }, { default: h(() => [(n(!0), m($, null, k(t.data.slides, p => (n(), x(d, { key: p.id }, { default: h(() => [e("div", Tn, [e("div", null, [e("h3", Mn, u(p.title), 1), (n(!0), m($, null, k(p.features, f => (n(), m("div", { key: f, class: "mb-4 flex items-start" }, [e("div", Sn, [_(s(he), { color: "#5CB660", size: 18 })]), e("p", In, u(f), 1)]))), 128))]), e("div", jn, [_(r, { src: ("useReplaceDomain" in o ? o.useReplaceDomain : s(v))(p.image.src), alt: p.image.alt }, null, 8, ["src", "alt"])])])]), _: 2 }, 1024))), 128))]), _: 1 }, 8, ["primary-title", "secondary-title"])]) } } }),
    Pn = { class: "text-center text-h4 text-text-primary sm:text-h3 md:text-h2" },
    Hn = { class: "mb-8 mt-4 text-center text-body1 text-text-secondary" },
    Rn = { class: "flex flex-col md:flex-row" },
    zn = ["innerHTML"],
    An = { class: "mb-2 text-h6 text-text-primary" },
    Nn = { class: "text-body2 text-text-secondary" },
    Fn = { class: "flex flex-col items-center justify-center gap-2 sm:flex-row" },
    En = b({ __name: "ApplicationProcess", props: { data: {} }, setup(l) { const t = l; return (o, c) => { const r = j,
                    d = S; return n(), m("div", null, [e("h2", Pn, u(t.data.title), 1), e("div", Hn, u(t.data.description), 1), e("div", Rn, [(n(!0), m($, null, k(t.data.items, i => (n(), m("div", { key: i.title, class: "mb-10 flex flex-1 flex-row items-start text-left md:flex-col md:items-center md:text-center" }, [e("div", { class: "mb-0 mr-5 md:mb-5 md:mr-0", innerHTML: i.icon }, null, 8, zn), e("div", null, [e("h3", An, u(i.title), 1), e("p", Nn, u(i.description), 1)])]))), 128))]), e("div", Fn, [(n(!0), m($, null, k(t.data.actionButtons, i => (n(), x(d, { key: i.content, "navigation-object": { link: i.link }, classes: "w-full sm:w-[180px]" }, { default: h(() => [_(r, { mode: i.mode, class: "flex w-full justify-center" }, { default: h(() => [B(u(i.content), 1)]), _: 2 }, 1032, ["mode"])]), _: 2 }, 1032, ["navigation-object"]))), 128))])]) } } }),
    Vn = (l, t, o, c) => { N({ script: [{ type: X, children: JSON.stringify({ "@context": "https://schema.org", "@type": "Product", name: t, description: l, image: v(c), sku: t, mpn: t, offers: { "@type": "AggregateOffer", availability: "InStock", priceValidUntil: `${new Date().getFullYear()}-12-31`, url: `${o}`, priceCurrency: "USD", lowPrice: "4.95", highPrice: "54.95", offerCount: 4 }, aggregateRating: { "@type": "AggregateRating", ratingCount: 75, ratingValue: 4.9, bestRating: "5", worstRating: "1" }, brand: { "@type": "Organization", name: "Cloudzy" }, review: { "@type": "Review", author: { "@type": "Person", name: "🥇Cloudzy🥇" } } }) }] }) },
    On = { key: 0 },
    Un = b({ __name: "TemplateLanding", async setup(l) { var z, U, y, W, q, Q; let t, o; const { params: c } = dt(), { fetchData: r } = xt(), d = w(() => { const A = Object.keys(a.pricing)[0]; return a.pricing[A][0].relatedProduct ? a.pricing[A][0].relatedProduct.priceItems[0].monthlyPrice : 0 }), { data: i, error: p } = ([t, o] = J(() => r(`/pages/landing/${c.slug}`)), t = await t, o(), t), f = w(() => ![ct.DevopsAsAService].includes(c.slug)), a = i ? i.data : {}; if ((p == null ? void 0 : p.data.statusCode) === 404) throw mt({ statusCode: 404, statusMessage: "Page Not Found" }); const M = w(() => c.slug === ct.Cloud);
            a && (ge(a.seo, (z = a == null ? void 0 : a.introduction) == null ? void 0 : z.image, (U = a == null ? void 0 : a.FAQ) == null ? void 0 : U.items), Vn((y = a.seo) == null ? void 0 : y.description, (W = a == null ? void 0 : a.pricing) == null ? void 0 : W[Object.keys(a.pricing)[0]][0].subtitle, c.slug, (Q = (q = a == null ? void 0 : a.introduction) == null ? void 0 : q.image) == null ? void 0 : Q.src)); const { fetchRegions: C, fetchProducts: D, processedPricing: E, products: V } = Jt(a.pricing), O = ([t, o] = J(() => C()), t = await t, o(), t); return [t, o] = J(() => D()), await t, o(), (A, nt) => { const Y = Ne,
                    Z = Ze,
                    G = xs,
                    K = ee,
                    gt = Xt,
                    tt = se,
                    ft = Ls,
                    bt = Ms,
                    yt = Zt,
                    vt = Vs,
                    wt = de,
                    $t = me,
                    kt = Qs,
                    Ct = _e,
                    Lt = tn,
                    Bt = Kt,
                    Tt = pn,
                    Mt = pe,
                    St = vn,
                    It = Ut,
                    jt = Dn,
                    Dt = En,
                    Pt = _t,
                    Ht = Wt,
                    Rt = F; return s(a) ? (n(), m("div", On, [_(Rt, null, { default: h(() => [s(a).unavailableBanner ? (n(), x(Y, { key: 0, data: s(a).unavailableBanner }, null, 8, ["data"])) : g("", !0), s(M) ? (n(), x(Z, { key: 1, data: s(a).hero, class: "mb-[100px] md:mb-[120px] lg:mb-[150px]" }, null, 8, ["data"])) : s(a).hero ? (n(), x(G, { key: 2, data: s(a).hero, class: "mb-[100px] md:mb-[120px] lg:mb-[150px]", "base-price": s(d) }, null, 8, ["data", "base-price"])) : g("", !0), s(a).startupHero ? (n(), x(K, { key: 3, class: "mb-[100px] md:mb-[120px] lg:mb-[150px]", data: s(a).startupHero }, null, 8, ["data"])) : g("", !0), s(a).pricing && s(V) ? (n(), x(gt, { key: 4, id: "pricing", data: s(E), class: "mb-[100px] md:mb-[120px] lg:mb-[150px]" }, null, 8, ["data"])) : g("", !0), s(a).introduction ? (n(), x(tt, { key: 5, data: s(a).introduction, class: "mb-[100px] md:mb-[120px] lg:mb-[150px]" }, null, 8, ["data"])) : g("", !0), s(a).serviceInformation ? (n(), x(ft, { key: 6, data: s(a).serviceInformation, class: "mb-[100px] md:mb-[120px] lg:mb-[150px]" }, null, 8, ["data"])) : g("", !0), s(a).hostAdvice ? (n(), x(bt, { key: 7, data: s(a).hostAdvice, class: "mb-[100px] md:mb-[120px] lg:mb-[150px]" }, null, 8, ["data"])) : g("", !0), s(a).whyChoose ? (n(), x(yt, { key: 8, data: s(a).whyChoose, class: "mb-[100px] md:mb-[120x] lg:mb-[150px]" }, null, 8, ["data"])) : g("", !0), s(a).payAsYouGo ? (n(), x(tt, { key: 9, data: s(a).payAsYouGo, class: "mb-[100px] md:mb-[120x] lg:mb-[150px]" }, null, 8, ["data"])) : g("", !0), s(a).vs ? (n(), x(vt, { key: 10, data: s(a).vs, class: "mb-[100px] md:mb-[120x] lg:mb-[150px]" }, null, 8, ["data"])) : g("", !0), s(a).whatOperatingSystems ? (n(), x(wt, { key: 11, data: s(a).whatOperatingSystems, class: "mb-[100px] md:mb-[120px] lg:mb-[150px]" }, null, 8, ["data"])) : g("", !0), s(a).platforms ? (n(), x($t, { key: 12, data: s(a).platforms, class: "mb-[100px] md:mb-[120px] lg:mb-[150px]" }, null, 8, ["data"])) : g("", !0), s(a).featuresCarousel ? (n(), x(kt, { key: 13, data: s(a).featuresCarousel, class: "mb-[100px] md:mb-[120px] lg:mb-[150px]" }, null, 8, ["data"])) : g("", !0), s(a).whenToChoose ? (n(), x(Ct, { key: 14, data: s(a).whenToChoose, class: "mb-[100px] md:mb-[120px]" }, null, 8, ["data"])) : g("", !0), s(a).howTo ? (n(), x(Lt, { key: 15, data: s(a).howTo, class: "mb-[100px] md:mb-[120px] lg:mb-[150px]" }, null, 8, ["data"])) : g("", !0), s(f) ? (n(), x(Bt, { key: 16, class: "mb-[100px] md:mb-[120px] lg:mb-[150px]", "default-active-tab": s(a).mapActiveTab, regions: s(O) }, null, 8, ["default-active-tab", "regions"])) : g("", !0), s(a).whenToBuy ? (n(), x(Tt, { key: 17, class: "mb-[100px] md:mb-[120px] lg:mb-[150px]", data: s(a).whenToBuy }, null, 8, ["data"])) : g("", !0), s(a).userFriendly ? (n(), x(Mt, { key: 18, class: "mb-[100px] md:mb-[120px] lg:mb-[150px]", data: s(a).userFriendly }, null, 8, ["data"])) : g("", !0), s(a).platformComparison ? (n(), x(tt, { key: 19, data: s(a).platformComparison, "is-title-on-top": !0, class: "mb-[100px] md:mb-[120x] lg:mb-[150px]" }, null, 8, ["data"])) : g("", !0), s(a).paymentMethods ? (n(), x(St, { key: 20, data: s(a).paymentMethods, class: "mb-[100px] md:mb-[120px] lg:mb-[150px]" }, null, 8, ["data"])) : g("", !0), s(a).testimonial ? (n(), x(It, { key: 21, data: s(a).testimonial, class: "mb-[100px] md:mb-[120px] lg:mb-[150px]" }, null, 8, ["data"])) : g("", !0), s(a).useCaseCarousel ? (n(), x(jt, { key: 22, data: s(a).useCaseCarousel, class: "mb-[100px] md:mb-[120px] lg:mb-[150px]" }, null, 8, ["data"])) : g("", !0), s(a).applicationProcess ? (n(), x(Dt, { key: 23, data: s(a).applicationProcess, class: "mb-[100px] md:mb-[120px] lg:mb-[150px]" }, null, 8, ["data"])) : g("", !0), s(a).FAQ ? (n(), x(Pt, { key: 24, data: s(a).FAQ, class: "mb-[100px] md:mb-[120px] lg:mb-[150px]" }, null, 8, ["data"])) : g("", !0), s(a).cta ? (n(), x(Ht, { key: 25, data: s(a).cta }, null, 8, ["data"])) : g("", !0)]), _: 1 })])) : g("", !0) } } }),
    Wn = { class: "flex w-full items-center gap-x-4 text-overline text-text-secondary" },
    qn = e("span", { class: "text text-grey-icon" }, " / ", -1),
    Qn = e("span", { class: "text text-grey-icon" }, " / ", -1),
    Yn = { class: "max-w-[30ch] truncate text-grey-400" },
    Gn = b({ __name: "BlogBreadcrumb", props: { title: {}, category: {} }, setup(l) { const t = l,
                c = { link: `${pt().public.SITE_URL}category/${t.category.link}` },
                r = { link: "/" }; return (d, i) => { const p = S; return n(), m("div", Wn, [_(p, { "navigation-object": r, class: "uppercase !text-text-secondary" }, { default: h(() => [B(" Home ")]), _: 1 }), qn, _(p, { "navigation-object": c, "target-blank": !0, class: "whitespace-nowrap uppercase !text-text-secondary" }, { default: h(() => [B(u(d.category.title), 1)]), _: 1 }), Qn, e("div", Yn, u(t.title), 1)]) } } }),
    Jn = { class: "flex items-center self-start" },
    Xn = { class: "mr-auto flex items-center lg:w-full" },
    Zn = { class: "flex flex-col" },
    Kn = { class: "text-subtitle1 text-text-primary lg:mb-1" },
    ta = ["innerHTML"],
    ea = b({ __name: "SidebarCTA", props: ["content"], setup(l) { const t = l,
                o = Nt(!0); return (c, r) => { const d = T,
                    i = j,
                    p = S; return n(), m("div", { class: L(["fixed bottom-0 left-0 z-10 flex w-full flex-col items-center justify-between border border-grey-200 bg-white-default p-4 sm:flex-row lg:static lg:mb-2 lg:flex-col lg:rounded-lg lg:shadow-16", { hidden: !s(o) }]) }, [e("div", Jn, [e("div", { class: "closeButtonOfCta mr-4 block cursor-pointer lg:hidden", onClick: r[0] || (r[0] = f => o.value = !1) }, [_(d, { src: ("useReplaceDomain" in c ? c.useReplaceDomain : s(v))("https://dev3.cloudzy.com/api/v1/static/listing/sidebarcta/crossCta.webp"), width: "12px", height: "12px", alt: t.content.image.alt }, null, 8, ["src", "alt"])]), e("div", Xn, [_(d, { class: "mr-4 h-[39px] w-[45px] lg:h-[48px] lg:w-[50px]", src: ("useReplaceDomain" in c ? c.useReplaceDomain : s(v))(t.content.image.src), alt: t.content.image.alt, width: "50px", height: "48px" }, null, 8, ["src", "alt"]), e("div", Zn, [e("p", Kn, u(t.content.title), 1), e("p", { class: "text-body2 text-text-secondary", innerHTML: t.content.description }, null, 8, ta)])])]), _(p, { "navigation-object": { link: t.content.link }, "target-blank": !0, class: L(["mt-2 w-full sm:w-[unset] lg:mt-4 lg:w-full", s(R).sidebarCTA]) }, { default: h(() => [_(i, { mode: "secondary", class: "flex h-[40px] w-full items-center lg:h-[32px]" }, { default: h(() => [B(" Check it Out ")]), _: 1 })]), _: 1 }, 8, ["navigation-object", "class"])], 2) } } }),
    sa = (l, t, o, c) => { N({ script: [{ type: X, children: JSON.stringify({ "@context": "https://schema.org", "@type": "NewsArticle", headline: l, image: t, datePublished: o, dateModified: o, author: [{ "@type": "Person", name: c.name, url: c.url ? c.url : void 0 }] }) }] }) },
    na = l => { const t = new Date(l); if (isNaN(t.getTime())) throw new TypeError("Invalid date format"); const o = t.getFullYear(),
            c = String(t.getMonth() + 1).padStart(2, "0"),
            r = String(t.getDate()).padStart(2, "0"),
            d = String(t.getHours()).padStart(2, "0"),
            i = String(t.getMinutes()).padStart(2, "0"),
            p = String(t.getSeconds()).padStart(2, "0"),
            f = String(t.getMilliseconds()).padStart(3, "0"); return `${o}-${c}-${r}T${d}:${i}:${p}.${f}Z` },
    aa = l => { N({ script: [{ type: X, children: JSON.stringify({ "@context": "https://schema.org", "@type": "VideoObject", name: l.name, description: l.description, thumbnailUrl: l.thumbnailUrl, duration: l.duration, contentUrl: l.contentUrl, embedUrl: l.embedUrl, uploadDate: l.uploadDate }) }] }) },
    oa = l => { N({ script: [{ type: X, children: JSON.stringify({ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: l.map((t, o) => ({ "@type": "ListItem", position: o + 1, name: t.name, item: t.link ? t.link : void 0 })) }) }] }) },
    ca = ["innerHTML"],
    ia = { __name: "HtmlRenderer", props: ["content"], setup(l) { const t = l; return (o, c) => (n(), m("div", { class: "mt-4", innerHTML: t.content }, null, 8, ca)) } },
    la = H(ia, [
        ["__scopeId", "data-v-7ea409ac"]
    ]),
    ra = { class: "relative flex flex-col rounded-lg bg-primary-dark p-4 sm:flex-row md:h-[174px]" },
    da = e("div", { class: "mb-2 text-subtitle2 text-orange-main sm:mb-4 sm:text-subtitle1" }, " Read ", -1),
    ma = { class: "text-subtitle1 text-white-default sm:text-h5" },
    pa = e("div", { class: "hidden w-[52px] items-center justify-center rounded bg-primary-main px-4 text-white-default md:-m-4 md:ml-auto md:flex" }, [e("svg", { xmlns: "http://www.w3.org/2000/svg", width: "18", height: "31", viewBox: "0 0 18 31", fill: "none" }, [e("path", { d: "M0.25 26.2768L10.9772 15.5625L0.25 4.84821L2.39544 0.5625L17.4135 15.5625L2.39544 30.5625L0.25 26.2768Z", fill: "white" })])], -1),
    ua = b({ __name: "ListingRelated", props: ["content"], setup(l) { const t = l,
                { title: o, img: c, link: r } = t.content; return (d, i) => { const p = T,
                    f = S; return n(), x(f, { id: s(R).listingRelated, class: "mt-4 block", "navigation-object": { link: s(r) }, "target-blank": !0 }, { default: h(() => [e("div", ra, [_(p, { class: "mb-2 w-full rounded-lg sm:mr-4 md:mb-0 md:w-[256px]", width: "280", height: "155", src: ("useReplaceDomain" in d ? d.useReplaceDomain : s(v))(s(c).src), alt: s(c).alt }, null, 8, ["src", "alt"]), e("div", null, [da, e("p", ma, u(s(o)), 1)]), pa])]), _: 1 }, 8, ["id", "navigation-object"]) } } }),
    _a = ["id"],
    xa = { class: "flex flex-col md:flex-row md:items-center md:gap-x-4" },
    ha = { class: "h-[102px] shrink-0 rounded-lg border border-solid border-grey-200 md:size-[102px]" },
    ga = { class: "flex h-full w-full items-center justify-center" },
    fa = ["src", "alt"],
    ba = { class: "mt-4 flex flex-wrap text-h5 text-text-primary md:mt-0" },
    ya = { class: "flex w-full" },
    va = { class: "mr-1" },
    wa = ["innerHTML"],
    $a = { key: 0, class: "mt-12 grid grid-cols-1 gap-10 sm:grid-cols-2 sm:gap-x-2.5 md:grid-cols-4" },
    ka = { class: "-mt-[26px] flex flex-col items-center" },
    Ca = { class: "size-[53px] rounded-full bg-grey-50 shadow-0.5" },
    La = { class: "flex h-full w-full items-center justify-center p-1" },
    Ba = { class: "mt-2 h-6 text-subtitle1 text-text-secondary" },
    Ta = ["innerHTML"],
    Ma = { __name: "CompanyComparison", props: ["content"], setup(l) { const t = l,
                o = t.content.name.toLowerCase() === "cloudzy" ? !0 : t.content.name.toLowerCase() === "🥇cloudzy",
                c = w(() => { var r, d; return (r = t.content) != null && r.id ? (d = t.content.id) == null ? void 0 : d.toLowerCase() : ht(t.content.name) }); return (r, d) => { const i = S,
                    p = T,
                    f = j; return n(), m("div", { id: s(c), class: "mt-4" }, [e("div", { class: L(["flex w-full flex-col rounded-lg px-4 py-5", s(o) ? "border-2 border-solid border-primary-main" : "shadow-1"]) }, [e("div", xa, [e("div", ha, [e("div", ga, [e("img", { src: ("useReplaceDomain" in r ? r.useReplaceDomain : s(v))(t.content.img.src), alt: t.content.name, class: "max-w-[80%]" }, null, 8, fa)])]), e("div", ba, [e("div", ya, [e("span", va, u(t.content.index) + ".", 1), e("h3", null, [_(i, { class: "text-link-main", "target-blank": !0, "navigation-object": s(o) ? { link: t.content.url } : { remoteLink: t.content.url } }, { default: h(() => [B(u(t.content.name), 1)]), _: 1 }, 8, ["navigation-object"])])]), e("div", { class: "mt-1 text-body2", innerHTML: t.content.info }, null, 8, wa)])]), t.content.features ? (n(), m("div", $a, [(n(!0), m($, null, k(t.content.features, (a, M) => (n(), m("div", { key: M, class: "relative flex h-20 basis-full flex-col items-center rounded bg-primary-light sm:grow sm:basis-auto" }, [e("div", ka, [e("div", Ca, [e("div", La, [_(p, { src: ("useReplaceDomain" in r ? r.useReplaceDomain : s(v))(a.icon.src), alt: a.icon.alt, width: "33" }, null, 8, ["src", "alt"])])]), e("div", Ba, u(a.title), 1)])]))), 128))])) : g("", !0), t.content.action ? (n(), x(i, { key: 1, id: "listingInlineCTA", "navigation-object": { link: t.content.action.url }, "target-blank": !0, class: "mt-6 flex w-fit basis-full justify-center self-center" }, { default: h(() => [_(f, { class: "w-full sm:max-w-[200px]" }, { default: h(() => [B(u(t.content.action.text), 1)]), _: 1 })]), _: 1 }, 8, ["navigation-object"])) : g("", !0)], 2), t.content.description ? (n(), m("div", { key: 0, class: "mt-6 text-body1 text-text-secondary", innerHTML: t.content.description }, null, 8, Ta)) : g("", !0)], 8, _a) } } },
    Sa = { class: "flex flex-wrap rounded border border-solid border-grey-200 bg-grey-50 p-6" },
    Ia = { class: "mb-4 flex items-center" },
    ja = { class: "text-justify text-body2 text-text-secondary" },
    Da = b({ __name: "ListingAuthor", props: { content: {} }, setup(l) { const t = l,
                o = w(() => `${pt().public.SITE_URL}author/emma`); return (c, r) => { const d = T,
                    i = S; return n(), m("div", Sa, [_(d, { class: "mb-4 mr-6 rounded-full sm:min-w-[80px]", height: "80", width: "80", src: ("useReplaceDomain" in c ? c.useReplaceDomain : s(v))(t.content.avatar.src), alt: t.content.avatar.alt }, null, 8, ["src", "alt"]), e("div", Ia, [_(i, { class: "text-subtitle1 !text-text-primary", "navigation-object": { link: s(o) }, "target-blank": !0 }, { default: h(() => [B(u(t.content.name), 1)]), _: 1 }, 8, ["navigation-object"])]), e("div", ja, u(t.content.bio), 1)]) } } }),
    Pa = { id: "faq" },
    Ha = b({ __name: "ListingFAQ", props: { content: {} }, setup(l) { const t = l; return (o, c) => { const r = _t; return n(), m("div", Pa, [_(r, { data: t.content, "break-in-two-column-on-lg": !1, "center-title": !1, "title-font-size": "text-h4", "accordion-title-font-size": "text-subtitle1" }, null, 8, ["data"])]) } } }),
    Ra = { class: "relative flex flex-col pt-[80px] text-white-default sm:flex-row sm:pl-[37%]" },
    za = { class: "flex h-1/2 w-full items-center justify-center bg-[url('assets/images/listing/cta/cta-top-bg.png')] bg-cover bg-center bg-no-repeat p-4 sm:absolute sm:left-0 sm:top-0 sm:h-[240px] sm:w-[37%] sm:flex-col sm:items-start" },
    Aa = { class: "text-h6 lg:text-h5" },
    Na = { class: "flex flex-col items-center bg-[url('assets/images/listing/cta/cta-bottom-bg.svg')] bg-cover bg-center bg-no-repeat p-4 text-center sm:h-[260px] sm:w-full sm:justify-between sm:p-8 lg:h-[218px]" },
    Fa = ["innerHTML"],
    Ea = b({ __name: "CallToAction", props: { content: {} }, setup(l) { const t = l; return (o, c) => { const r = T,
                    d = j,
                    i = S; return n(), m("div", Ra, [e("div", za, [_(r, { src: ("useReplaceDomain" in o ? o.useReplaceDomain : s(v))(t.content.image.src), alt: t.content.image.alt, width: "71", height: "71", class: "mr-4 sm:mb-4" }, null, 8, ["src", "alt"]), e("p", Aa, u(t.content.title), 1)]), e("div", Na, [e("p", { class: "mb-4 text-body1", innerHTML: t.content.description }, null, 8, Fa), _(i, { id: t.content.button.content, class: L(s(R).listingCallToAction), "navigation-object": { link: t.content.button.link }, "target-blank": !0 }, { default: h(() => [_(d, { mode: "secondary" }, { default: h(() => [B(u(t.content.button.content), 1)]), _: 1 })]), _: 1 }, 8, ["id", "class", "navigation-object"])])]) } } }),
    Va = ["id"],
    Oa = ["innerHTML"],
    Ua = ["innerHTML"],
    Wa = ["innerHTML"],
    qa = b({ __name: "IconTitleDesc", props: { content: {} }, setup(l) { const t = l,
                o = w(() => t.content.id ? t.content.id : t.content.title.split(" ").join("-").toLowerCase()),
                c = w(() => t.content.vertical); return (r, d) => { const i = T,
                    p = S; return n(), m("div", { id: s(o), class: L(["flex", s(c) ? "" : "flex-wrap"]) }, [e("div", { class: L(["flex", s(c) ? "mr-4 min-w-40 flex-col items-center" : "flex-row"]) }, [t.content.image ? (n(), x(i, { key: 0, src: t.content.image.src, alt: t.content.image.alt, class: L(["mt-0 flex h-[28px] w-[28px] items-center", s(c) ? "h-[56px] w-[56px]" : ""]) }, null, 8, ["src", "alt", "class"])) : (n(), m("div", { key: 1, class: "mt-0 flex h-[28px] w-[28px] items-center", innerHTML: t.content.icon }, null, 8, Oa)), e("h3", { class: L(["text-h6 text-text-primary", s(c) ? "ml-0 mt-4 text-center text-subtitle1" : "ml-2"]) }, [t.content.navigationObject ? (n(), x(p, { key: 0, "navigation-object": {...t.content.navigationObject }, "target-blank": !0, classes: "w-full sm:w-[180px]" }, { default: h(() => [B(u(t.content.title), 1)]), _: 1 }, 8, ["navigation-object"])) : (n(), m("span", { key: 1, innerHTML: t.content.title }, null, 8, Ua))], 2)], 2), e("div", { class: L(["text-body1 text-text-secondary", s(c) ? "mt-0" : "mt-3 w-full"]), innerHTML: t.content.description }, null, 10, Wa)], 10, Va) } } }),
    Qa = { class: "mt-4 flex w-full flex-wrap justify-between gap-2 md:gap-0" },
    Ya = { class: "flex basis-full flex-col gap-y-2 md:basis-1/2" },
    Ga = e("span", { class: "mb-1 text-subtitle1" }, " Pros ", -1),
    Ja = { class: "text-body1" },
    Xa = { class: "flex basis-full flex-col gap-y-2 md:basis-1/2" },
    Za = e("span", { class: "mb-1 text-subtitle1" }, " Cons ", -1),
    Ka = { class: "text-body1" },
    to = b({ __name: "ProsAndCons", props: { content: {} }, setup(l) { const t = l; return (o, c) => (n(), m("div", Qa, [e("div", Ya, [Ga, (n(!0), m($, null, k(t.content.pros, (r, d) => (n(), m("div", { key: d, class: "flex items-center gap-x-2" }, [_(s(Le), { class: "h-[18px] w-[18px] text-green-main" }), e("span", Ja, u(r), 1)]))), 128))]), e("div", Xa, [Za, (n(!0), m($, null, k(t.content.cons, (r, d) => (n(), m("div", { key: d, class: "flex items-center gap-x-2" }, [_(s(Ie), { class: "h-[18px] w-[18px] text-red-main" }), e("span", Ka, u(r), 1)]))), 128))])])) } }),
    eo = ["id"],
    so = ["src"],
    no = b({ __name: "ListingVideo", props: { content: {} }, setup(l) { const t = l,
                o = t.content.title ? ht(t.content.title) : ""; return (c, r) => (n(), m("div", null, [t.content.title ? (n(), m("h2", { key: 0, id: s(o), class: "mb-4 text-h4 text-text-primary md:mb-6" }, u(t.content.title), 9, eo)) : g("", !0), e("iframe", { class: "min-h-[250px] w-full md:h-[450px]", src: t.content.src, title: "YouTube video player", frameborder: "0", allow: "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share", referrerpolicy: "strict-origin-when-cross-origin", allowfullscreen: "" }, null, 8, so)])) } }),
    ao = b({ __name: "ListingImage", props: { content: {} }, setup(l) { return (t, o) => { var r, d, i, p; const c = T; return n(), x(c, { loading: "lazy", src: (r = t.content) == null ? void 0 : r.src, alt: (d = t.content) == null ? void 0 : d.alt, width: (i = t.content) == null ? void 0 : i.width, height: (p = t.content) == null ? void 0 : p.height }, null, 8, ["src", "alt", "width", "height"]) } } }),
    oo = { key: 0, class: "w-full pb-28 pt-10 sm:pb-24 lg:pb-0" },
    co = { class: "mb-4 text-h4 text-text-primary md:mb-8 md:text-h2" },
    io = { class: "listing-wrapper" },
    lo = { class: "feature-box" },
    ro = { class: "content-box" },
    mo = { class: "sidebar-box lg:sticky lg:top-[140px] lg:ml-6" },
    po = { class: "mt-32 bg-primary-soft pb-2 pt-20" },
    uo = b({ __name: "TemplateListing", async setup(l) { let t, o; const { params: c } = dt(), { fetchData: r } = xt(), { data: d, error: i } = ([t, o] = J(() => r(`/pages/${ve.Blog}/${c.slug}`)), t = await t, o(), t); if ((i == null ? void 0 : i.statusCode) === 404) throw mt({ statusCode: 404, statusMessage: "Page Not Found" }); const p = d.data,
                f = y => ({ html: la, related: ua, company: Ma, author: Da, faq: Ha, cta: Ea, pricing: ce, IconTitleDesc: qa, ProsAndCons: to, compare: ie, accordion: le, blogTable: re, video: no, image: ao })[y] || "DefaultComponent",
                a = w(() => p.find(y => y.type === "feature")),
                M = w(() => p.find(y => y.type === "comments") ? ? { comments: [] }),
                C = w(() => p.find(y => y.type === "seo"));
            N({ title: C.value.content.seoTitle }); const D = w(() => p.filter(y => y.type === "breadCrumb")[0]),
                E = w(() => p.filter(y => y.type === "sidebarCta")[0]),
                V = w(() => p.filter(y => y.type === "toc")[0]),
                O = w(() => p.find(y => y.type === "faq")),
                z = w(() => p.find(y => y.type === "author"));
            O.value && fe(O.value.content.items), C.value && a.value && be(C.value.content.title, C.value.content.description, a.value.content.headerImage.src, { width: 728, height: 404 }, C.value.content.seoTitle), C.value && a.value && z.value && sa(C.value.content.title, a.value.content.headerImage.src, na(a.value.content.updatedAt), z.value.content), C.value.content.video && aa(C.value.content.video), ye(), D.value && oa([{ name: "Home", link: "" }, { name: D.value.content.category.title, link: "category/" + D.value.content.category.link }, { name: C.value.content.title }]); const U = { title: "Latest Blog Posts", slides: [{ link: "best-mail-servers-for-windows/", image: { src: "https://dev3.cloudzy.com/api/v1/static/listing/feature/Best-Mail-Servers-for-Windows-new.webp", alt: "Best-Mail-Servers-for-Windows" }, context: "8 Best Mail Servers for Windows 2024", info: { date: "13 mins read", name: "Emma Bennet", avatar: { src: "https://dev3.cloudzy.com/api/v1/static/listing/authors/emma-bennet.webp", alt: "Emma Bennet" } } }, { link: "best-linux-vpn/", image: { src: "https://dev3.cloudzy.com/api/v1/static/listing/feature/Best-Linux-Mail-Servers.webp", alt: "best vps hosting providers" }, context: "Best Linux VPS [Top 10 Linux VPS Provider 2024]", info: { date: "20 mins read", name: "Emma Bennet", avatar: { src: "https://dev3.cloudzy.com/api/v1/static/listing/authors/emma-bennet.webp", alt: "Emma Bennet" } } }, { link: "best-vps-for-vpn/", image: { src: "https://dev3.cloudzy.com/api/v1/static/listing/feature/Best-Windows-VPS-new.webp", alt: "best vps hosting for wordpress" }, context: "10 Best VPS For VPN in 2024 [Your Own VPN Server Hosting]", info: { date: "18 mins read", name: "Emma Bennet", avatar: { src: "https://dev3.cloudzy.com/api/v1/static/listing/authors/emma-bennet.webp", alt: "Emma Bennet" } } }, { link: "best-linux-mail-servers/", image: { src: "api/v1/static/listing/feature/Best-Linux-Mail-Servers.webp", alt: "Best-Linux-Mail-Servers" }, context: "14 Best Linux Mail Servers in 2024 (Free + Open Source)", info: { date: "14 mins read", name: "Emma Bennet", avatar: { src: "https://dev3.cloudzy.com/api/v1/static/listing/authors/emma-bennet.webp", alt: "Emma Bennet" } } }] }; return (y, W) => { const q = Gn,
                    Q = ae,
                    A = ea,
                    nt = oe,
                    Y = F,
                    Z = qt; return s(d) ? (n(), m("div", oo, [_(Y, null, { default: h(() => [s(D) ? (n(), x(q, { key: 0, title: s(C).content.title, category: s(D).content.category, class: "mb-4" }, null, 8, ["title", "category"])) : g("", !0), e("h1", co, u(s(C).content.title), 1), e("div", io, [e("div", lo, [_(ne, { content: s(a).content, class: "" }, null, 8, ["content"])]), e("div", ro, [(n(!0), m($, null, k(s(p), (G, K) => (n(), m("div", { key: K, class: "w-full" }, [(n(), x(rt(f(G.type)), { content: G.content, class: "mb-5" }, null, 8, ["content"]))]))), 128))]), _(Q, { class: "order-4 mt-10 w-full", content: s(M) }, null, 8, ["content"]), e("div", mo, [s(E) ? (n(), x(A, { key: 0, content: s(E).content }, null, 8, ["content"])) : g("", !0), s(V) ? (n(), x(nt, { key: 1, content: s(V).content }, null, 8, ["content"])) : g("", !0)])])]), _: 1 }), e("div", po, [_(Y, null, { default: h(() => [_(Z, { data: U })]), _: 1 })])])) : g("", !0) } } }),
    _o = H(uo, [
        ["__scopeId", "data-v-0bc489e2"]
    ]),
    Zo = b({ __name: "[slug]", setup(l) { const { isLanding: t, isListing: o } = we(); return (c, r) => { const d = Un,
                    i = _o; return n(), m("div", null, [s(t) ? (n(), x(d, { key: 0 })) : g("", !0), s(o) ? (n(), x(i, { key: 1 })) : g("", !0)]) } } });
export { Zo as default };